=== seunyboyxu/Orpheus/Orpheus/bin/Debug/MidiDataSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TheMidiFile",
  "type": "object",
  "properties": {
    "filename": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "bpm": {
      "type": "number",
      "minimum": 0
    },
    "TimeSig": {
      "type": "string"
    },
    "Top10Notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "AllNotesUsed": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "patterns": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number",
          "minimum": 0
        }
      }
    }
  },
  "required": [
    "filename",
    "location",
    "bpm",
    "TimeSig",
    "Top10Notes",
    "AllNotesUsed",
    "patterns"
  ]
}

=== seunyboyxu/Orpheus/Orpheus/bin/Debug/MidiData/MidiData_717.json
[
  {
    "filename": "K330-1.mid",
    "location": "/Users/seun_/source/repos/Orpheus/Orpheus_Analyser/bin/Debug/midi file list\\K\\K\\K330-1.mid",
    "bpm": 120,
    "TimeSig": "4/4",
    "Top10Notes": [
      "G3",
      "B3",
      "C4",
      "E4",
      "G4",
      "B4",
      "C5",
      "D5",
      "E5",
      "G5"
    ],
    "AllNotesUsed": [
      "G2",
      "B2",
      "C3",
      "C#3",
      "D3",
      "D#3",
      "E3",
      "F3",
      "F#3",
      "G3",
      "G#3",
      "A3",
      "A#3",
      "B3",
      "C4",
      "C#4",
      "D4",
      "D#4",
      "E4",
      "F4",
      "F#4",
      "G4",
      "G#4",
      "A4",
      "A#4",
      "B4",
      "C5",
      "C#5",
      "D5",
      "D#5",
      "E5",
      "F5",
      "F#5",
      "G5",
      "G#5",
      "A5",
      "A#5",
      "B5",
      "C6",
      "D6",
      "E6",
      "F6"
    ],
    "patterns": [
      [
        0.40999999999999998,
        0.20999999999999999,
        0.20999999999999999,
        0.17000000000000001,
        0.089999999999999997,
        0.070000000000000007,
        0.10000000000000001,
        0.050000000000000003,
        0.029999999999999999,
        0.040000000000000001,
        0.029999999999999999,
        0.029999999999999999,
        0.059999999999999998,
        0.040000000000000001,
        0.040000000000000001,
        0.050000000000000003
      ]
    ]
  },
  {
    "filename": "K330-2.mid",
    "location": "/Users/seun_/source/repos/Orpheus/Orpheus_Analyser/bin/Debug/midi file list\\K\\K\\K330-2.mid",
    "bpm": 120,
    "TimeSig": "4/4",
    "Top10Notes": [
      "F3",
      "A3",
      "A#3",
      "C4",
      "F4",
      "G4",
      "A4",
      "A#4",
      "C5",
      "F5"
    ],
    "AllNotesUsed": [
      "B1",
      "C2",
      "D2",
      "E2",
      "F2",
      "G2",
      "G#2",
      "A2",
      "A#2",
      "B2",
      "C3",
      "C#3",
      "D3",
      "D#3",
      "E3",
      "F3",
      "G3",
      "G#3",
      "A3",
      "A#3",
      "B3",
      "C4",
      "C#4",
      "D4",
      "D#4",
      "E4",
      "F4",
      "F#4",
      "G4",
      "G#4",
      "A4",
      "A#4",
      "B4",
      "C5",
      "C#5",
      "D5",
      "D#5",
      "E5",
      "F5",
      "G5",
      "G#5",
      "A5",
      "A#5",
      "B5",
      "C6"
    ],
    "patterns": [
      [
        0.33000000000000002,
        0.17999999999999999,
        0.11,
        0.17000000000000001,
        0.11,
        0.059999999999999998,
        0.040000000000000001,
        0.029999999999999999,
        0.059999999999999998,
        0.070000000000000007,
        0.070000000000000007,
        0.050000000000000003,
        0.029999999999999999,
        0.029999999999999999,
        0.029999999999999999,
        0.12
      ]
    ]
  },
  {
    "filename": "K330-3.mid",
    "location": "/Users/seun_/source/repos/Orpheus/Orpheus_Analyser/bin/Debug/midi file list\\K\\K\\K330-3.mid",
    "bpm": 120,
    "TimeSig": "4/4",
    "Top10Notes": [
      "G3",
      "B3",
      "C4",
      "D4",
      "G4",
      "C5",
      "D5",
      "E5",
      "F5",
      "G5"
    ],
    "AllNotesUsed": [
      "C2",
      "E2",
      "F2",
      "G2",
      "A2",
      "A#2",
      "B2",
      "C3",
      "C#3",
      "D3",
      "E3",
      "F3",
      "F#3",
      "G3",
      "G#3",
      "A3",
      "A#3",
      "B3",
      "C4",
      "C#4",
      "D4",
      "D#4",
      "E4",
      "F4",
      "F#4",
      "G4",
      "G#4",
      "A4",
      "A#4",
      "B4",
      "C5",
      "C#5",
      "D5",
      "D#5",
      "E5",
      "F5",
      "F#5",
      "G5",
      "G#5",
      "A5",
      "A#5",
      "B5",
      "C6",
      "D6",
      "D#6",
      "E6",
      "F6"
    ],
    "patterns": [
      [
        0.029999999999999999,
        0.53000000000000003,
        0.33000000000000002,
        0.17000000000000001,
        0.089999999999999997,
        0.050000000000000003,
        0.17000000000000001,
        0.089999999999999997,
        0.050000000000000003,
        0.050000000000000003,
        0.070000000000000007,
        0.11,
        0.059999999999999998,
        0.040000000000000001,
        0.02,
        0.02
      ]
    ]
  }
]
